### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by mgmax** [fau-fablab/festool-kreissaege-einweisung#2]
Die Bilder sind von Festool, der Text klingt stellenweise auch sehr ähnlich wie die Anleitung. Dies muss klar gekennzeichnet werden! Bisher steht irgendwas von (C) FAU FabLab im Dokument, was so sicher nicht stimmt.

**Comment by ep092** [comment]
Am 20. Oktober 2015 um 19:39 schrieb Max Gaukler notifications@github.com:

> Die Bilder sind von Festool, der Text klingt stellenweise auch sehr
> ähnlich wie die Anleitung.
> 
> richtig
> 
> Dies muss klar gekennzeichnet werden!
> 
> Sollte es nicht reichen das am Ende des Dokuments zu machen
> 
> Bisher steht irgendwas von (C) FAU FabLab im Dokument, was so sicher nicht
> stimmt.
> 
> wo?

Viele Grüße
Toni

**Comment by mgmax** [comment]
Ganz oben im Quelltext steht der von mir kritisierte Copyrighthinweis.
Die Anleitung ist lediglich ganz am Ende als Quelle angegeben. Du 
solltest von deiner Bachelorarbeit kennen, dass ein gewaltiger 
Unterschied zwischen "Quelle" und "nahezu unverändert übernommen" 
besteht. Letzteres geht nur im Rahmen des Zitatrechts, bei direkter 
Kennzeichnung aller zitierten Stellen, und auch nur in eingeschränktem 
Umfang.
